gui: 
  hot-keys:
    <alt><space>: show
    <super>r: run
    <super>t: tr

using:
  - buildin
  - buildin.tools
  - buildin.apps
  - buildin.filter

services:
  store:
    file: ~/.config/copilot/store.db
  socketio:
    port: 9991

processors : 
  buildin.apps[linux]:
    launch: gtk-launch
    icon: \.png$|\.jpg$
    icons:
      - ~/.local/share/icons/hicolor/48x48/apps
      - /usr/share/icons/hicolor/48x48/apps
      - /usr/share/pixmaps
    path:
      # - ~/Desktop
      - ~/.local/share/applications
      - /usr/share/applications
  buildin.win.list: 
    desc: list all windows
  buildin.filter.grep:
    desc: grep input list
    op:
      i:
        help: ignore case
        action: count
  buildin.dict.oxford:
    id: "b0b6ca74"
    key: "1a839d68846b6bb4efe7a04745966233"
    trigger: $
    url:  https://od-api.oxforddictionaries.com/api/v1/entries/en/{word}
  buildin.dict.iciba:
    key: "1EB6995440B5FFC5BA2343BAD34D32F6"
    trigger: $
    url: http://dict-co.iciba.com/api/dictionary.php?w={word}&type=json&key=1EB6995440B5FFC5BA2343BAD34D32F6

# processorsInfo & aliasInfo description
# Structure
# [name]:
#   icon: name or path of a image file (letter and digital and dot only)
#   text: what text to show
#   value what value to use (in search or grep,if missed using text as value)
#   options:  #options help info
#     [op]:[value]
#   args:  # cli-argparser's option config

processorsInfo:
  buildin.apps.list:
    text: list all apps
  buildin.apps.launch:
    text: launch 
  buildin.tools.head:
    text: head <number>, select first nth items.
  buildin.tools.tail:
    text: tail <number>, select last nth items.
  buildin.tools.toPipe:
    text: toPipe --title <title> --value <value> --text <text>, put into pipe
    options:
      --title: Display title
      --value: Value
      --text: Display text
  buildin.tools.now:
    text: Show time
  buildin.tools.count:
    text: Count items
  buildin.win.list:
    text: list all windows
  buildin.win.active:
    text: active window
  buildin.win.close:
    text: close window
  buildin.win.move:
    text: move x y, move window to (x,y)
  buildin.process.list:
    text: list all process
  buildin.process.kill:
    text: kill <signal> process
    options:
      signal: INT,KILL and so on
  buildin.other.lucky:
    icon: buildin.funny
    text: Does YY lucky?
  buildin.other.who:
    icon: buildin.funny
    text: who --who p1 p2 ... --something , who doing something
    args:
      who:
        type: list
      something:
        type: string
  buildin.filter.grep:
    text: grep [-i] <text>, filter items by RegExp
    options:
      -i: ignore cases
      --field: specify which field to search
  buildin.filter.search:
    text: search [--keys <val1,val2>], fuzzy search items
    options:
      --keys: specify fields to search
  buildin.tools.copy:
    text: copy [value|--field field] copy field to clipboard
    options:
      field: title , value , text
  buildin.dict.oxford:
    text: oxford dictionary
  buildin.tools.cmd:
    title: Execute a cmd
    text: cmd --title <title> --text <text> --value <value> --cmd <cmd> args,
    


    
alias:
  wins: buildin.win.list
  first: head 1
  last: tail 1
  n: head __arg__ | last
  a: wins | grep -i __arg__ | buildin.win.active
  close: wins | buildin.win.close | search __arg__
  wm: wins | search __arg__ | buildin.win.move __arg0__ __arg1__
  run: buildin.apps.list | search __arg__ | buildin.apps.launch
  callme: buildin.tools.toPipe --title "Call me to do ..." --text __arg__ --value __arg__ | buildin.tools.notify | buildin.tools.timeout __arg0__ __arg1__
  kill: buildin.process.list | buildin.process.kill | grep __arg_
  npmjs: buildin.tools.toPipe --title "Search in npmjs" --text "Search __arg__ in npmjs" --value "https://www.npmjs.com/search?q=__arg__" | buildin.file.open
  github: buildin.tools.toPipe --title "Search in github" --text "Search __arg__ in github" --value "https://github.com/search?q=__arg__" | buildin.file.open
  google: buildin.tools.toPipe --title "Search by google" --text "Search __arg__ by google" --value "https://www.google.com.sg/search?q=__arg__" | buildin.file.open
  bing: buildin.tools.toPipe --title "Search by bing" --text "Search __arg__ by bing"  --value "https://www.bing.com/search?q=__arg__" | buildin.file.open 
  oxford: buildin.dict.oxford

aliasInfo:
  wins:
    text: list all windows
  first:
    text: select first item
  last:
    text: select last item
  n:
    text: n <number> select nth item
  a:
    text: a <text>, active window matched by text
  close:
    text: close <text>, close window matched by text
  wm:
    text: wm <text>, move window to (0,0) matched by text
  run:
    text: run <text>, launch app matched by text
  callme:
    text: callme <[--min|--sec] number> <something> , Call me to do something.
  kill:
    text: kill <text>, kill process matched by text
  npmjs:
    text: npmjs <text>, search in npmjs
  github:
    text: github <text>, search in github
    icon: buildin.github
  google:
    text: google <text>, search by google
    icon: buildin.google
  bing:
    text: bing <text>, search by bing
    icon: buildin.bing
  oxford:
    text: Oxford dict
    icon: buildin.dict.oxford